# Generated by Django 4.2.7 on 2023-11-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_user_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
